package com.ferullogaming.countercraft.block;

import com.ferullogaming.countercraft.block.decal.BlockDecal;
import com.ferullogaming.countercraft.block.emmiter.BlockEmitterSound;
import com.ferullogaming.countercraft.block.prop.BlockPropBarrel;
import com.ferullogaming.countercraft.block.prop.BlockPropCrateMetal;
import com.ferullogaming.countercraft.block.prop.BlockPropCrateWood;
import com.ferullogaming.countercraft.block.prop.BlockPropTable;
import com.ferullogaming.countercraft.block.prop.TileEntityPropBarrel;
import com.ferullogaming.countercraft.block.prop.TileEntityPropCrateMetal;
import com.ferullogaming.countercraft.block.prop.TileEntityPropCrateWood;
import cpw.mods.fml.common.registry.GameRegistry;
import cpw.mods.fml.common.registry.LanguageRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.BlockHalfSlab;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraft.item.ItemDye;
import net.minecraft.item.ItemSlab;
import net.minecraft.item.ItemStack;

public class BlockManager {
   public static Block mapBarrier;
   public static Block benchMenu;
   public static Block propCrateWood;
   public static Block propCrateMetal;
   public static Block propBarrel;
   public static Block propTable;
   public static Block emitterSoundBirds;
   public static Block emitterSoundWind;
   public static Block emitterSoundWar;
   public static Block emitterSoundHelicopter;
   public static Block emitterSoundDog;
   public static Block emitterSoundNight;
   public static Block emitterSoundCity;
   public static Block emitterSoundShop;
   public static Block road;
   public static Block roadSolid;
   public static Block roadBroken;
   public static Block sandbag;
   public static Block brick1;
   public static Block brick2;
   public static Block concrete;
   public static Block carpet1;
   public static Block carpet2;
   public static Block carpet3;
   public static Block hazard1;
   public static Block hazard2;
   public static Block rust1;
   public static Block grate1;
   public static Block grate2;
   public static Block stone1;
   public static Block stone2;
   public static Block stone3;
   public static Block stone4;
   public static Block stone5;
   public static Block stone6;
   public static Block stone7;
   public static Block stone8;
   public static Block light;
   public static Block decalSiteA;
   public static Block decalSiteB;
   public static Block decalArrowUp;
   public static Block decalArrowDown;
   public static Block decalArrowLeft;
   public static Block decalArrowRight;
   public static BlockHalfSlab stainedClayDoubleSlab;
   public static BlockHalfSlab stainedClaySlab;
   public static BlockHalfSlab stainedClayDoubleSlab2;
   public static BlockHalfSlab stainedClaySlab2;
   public static Block metalPlatform;
   public static Block glassSlab;

   public void init() {
      propCrateWood = (new BlockPropCrateWood(1502)).setHardness(0.3F).setUnlocalizedName("cratewood");
      GameRegistry.registerBlock(propCrateWood, "cc.block.props.cratewood");
      LanguageRegistry.addName(propCrateWood, "Wooden Crate");
      propCrateMetal = (new BlockPropCrateMetal(1503)).setHardness(0.3F).setUnlocalizedName("cratemetal");
      GameRegistry.registerBlock(propCrateMetal, "cc.block.props.cratemetal");
      LanguageRegistry.addName(propCrateMetal, "Metal Crate");
      propBarrel = (new BlockPropBarrel(1504)).setHardness(0.3F).setUnlocalizedName("barrel");
      GameRegistry.registerBlock(propBarrel, "cc.block.props.barrel");
      LanguageRegistry.addName(propBarrel, "Barrel");
      propTable = (new BlockPropTable(1505)).setHardness(0.3F).setUnlocalizedName("table");
      GameRegistry.registerBlock(propTable, "cc.block.props.table");
      LanguageRegistry.addName(propTable, "Table");
      road = (new BlockCC(1040)).setCDTexture("road").setHardness(2.0F).setUnlocalizedName("road");
      roadBroken = (new BlockRoad(1041, "broken")).setHardness(2.0F).setUnlocalizedName("road.broken");
      roadSolid = (new BlockRoad(1042, "solid")).setHardness(2.0F).setUnlocalizedName("road.solid");
      sandbag = (new BlockCC(1251)).setCDTexture("sandbag").setHardness(2.0F).setUnlocalizedName("sandbag");
      brick1 = (new BlockCC(1252)).setCDTexture("brick1").setHardness(2.0F).setUnlocalizedName("brick1");
      GameRegistry.registerBlock(brick1, "cc.block.brick1");
      LanguageRegistry.addName(brick1, "Brick Wall");
      brick2 = (new BlockCC(1253)).setCDTexture("brick2").setHardness(2.0F).setUnlocalizedName("brick2");
      GameRegistry.registerBlock(brick2, "cc.block.brick2");
      LanguageRegistry.addName(brick2, "Old Brick Wall");
      concrete = (new BlockCC(1254)).setCDTexture("concrete").setHardness(2.0F).setUnlocalizedName("concrete");
      GameRegistry.registerBlock(concrete, "cc.block.concrete");
      LanguageRegistry.addName(concrete, "Concrete Block");
      carpet1 = (new BlockCC(1255)).setCDTexture("carpet1").setHardness(2.0F).setUnlocalizedName("carpet1");
      GameRegistry.registerBlock(carpet1, "cc.block.carpet1");
      LanguageRegistry.addName(carpet1, "Dark Carpet");
      carpet2 = (new BlockCC(1256)).setCDTexture("carpet2").setHardness(2.0F).setUnlocalizedName("carpet2");
      GameRegistry.registerBlock(carpet2, "cc.block.carpet2");
      LanguageRegistry.addName(carpet2, "Carpet");
      carpet3 = (new BlockCC(1257)).setCDTexture("carpet3").setHardness(2.0F).setUnlocalizedName("carpet3");
      GameRegistry.registerBlock(carpet3, "cc.block.carpet3");
      LanguageRegistry.addName(carpet3, "Light Carpet");
      hazard1 = (new BlockCC(1258)).setCDTexture("hazard1").setHardness(2.0F).setUnlocalizedName("hazard1");
      GameRegistry.registerBlock(hazard1, "cc.block.hazard1");
      LanguageRegistry.addName(hazard1, "Hazard Block (Orange and White)");
      hazard2 = (new BlockCC(1259)).setCDTexture("hazard2").setHardness(2.0F).setUnlocalizedName("hazard2");
      GameRegistry.registerBlock(hazard2, "cc.block.hazard2");
      LanguageRegistry.addName(hazard2, "Hazard Block (Gray and Yellow)");
      rust1 = (new BlockCC(1260)).setCDTexture("rust1").setHardness(2.0F).setUnlocalizedName("rust1");
      GameRegistry.registerBlock(rust1, "cc.block.rust1");
      LanguageRegistry.addName(rust1, "Rusted Block");
      grate1 = (new BlockCC(1261)).setCDTexture("grate1").setHardness(2.0F).setUnlocalizedName("grate1");
      GameRegistry.registerBlock(grate1, "cc.block.grate1");
      LanguageRegistry.addName(grate1, "Rusty Grate");
      grate2 = (new BlockCC(1262)).setCDTexture("grate2").setHardness(2.0F).setUnlocalizedName("grate2");
      GameRegistry.registerBlock(grate2, "cc.block.grate2");
      LanguageRegistry.addName(grate2, "Dotted Rusty Grate");
      stone1 = (new BlockCC(1263)).setCDTexture("stone1").setHardness(2.0F).setUnlocalizedName("stone1");
      GameRegistry.registerBlock(stone1, "cc.block.stone1");
      LanguageRegistry.addName(stone1, "Stone Block");
      stone2 = (new BlockCC(1264)).setCDTexture("stone2").setHardness(2.0F).setUnlocalizedName("stone2");
      GameRegistry.registerBlock(stone2, "cc.block.stone2");
      LanguageRegistry.addName(stone2, "Stone Block");
      stone3 = (new BlockCC(1265)).setCDTexture("stone3").setHardness(2.0F).setUnlocalizedName("stone3");
      GameRegistry.registerBlock(stone3, "cc.block.stone3");
      LanguageRegistry.addName(stone3, "Stone Block");
      stone4 = (new BlockCC(1266)).setCDTexture("stone4").setHardness(2.0F).setUnlocalizedName("stone4");
      GameRegistry.registerBlock(stone4, "cc.block.stone4");
      LanguageRegistry.addName(stone4, "Stone Block");
      stone5 = (new BlockCC(1267)).setCDTexture("stone5").setHardness(2.0F).setUnlocalizedName("stone5");
      GameRegistry.registerBlock(stone5, "cc.block.stone5");
      LanguageRegistry.addName(stone5, "Stone Block");
      stone6 = (new BlockCC(1268)).setCDTexture("stone6").setHardness(2.0F).setUnlocalizedName("stone6");
      GameRegistry.registerBlock(stone6, "cc.block.stone6");
      LanguageRegistry.addName(stone6, "Stone Block");
      stone7 = (new BlockCC(1269)).setCDTexture("stone7").setHardness(2.0F).setUnlocalizedName("stone7");
      GameRegistry.registerBlock(stone7, "cc.block.stone7");
      LanguageRegistry.addName(stone7, "Stone Block");
      stone8 = (new BlockCC(1270)).setCDTexture("stone8").setHardness(2.0F).setUnlocalizedName("stone8");
      GameRegistry.registerBlock(stone8, "cc.block.stone8");
      LanguageRegistry.addName(stone8, "Stone Block");
      light = (new BlockLightCC(1271)).setCDTexture("light").setHardness(2.0F).setUnlocalizedName("light");
      GameRegistry.registerBlock(light, "cc.block.light");
      LanguageRegistry.addName(light, "Light Block");
      stainedClayDoubleSlab = (BlockHalfSlab)(new BlockClaySlab(1050, true, true)).setUnlocalizedName("stainedclaydoubleslab");
      stainedClaySlab = (BlockHalfSlab)(new BlockClaySlab(1051, false, true)).setUnlocalizedName("stainedclayslab");
      stainedClayDoubleSlab2 = (BlockHalfSlab)(new BlockClaySlab(1052, true, false)).setSecond().setUnlocalizedName("stainedclaydoubleslab2");
      stainedClaySlab2 = (BlockHalfSlab)(new BlockClaySlab(1053, false, false)).setSecond().setUnlocalizedName("stainedclayslab2");
      metalPlatform = (new BlockSlabOpaqueCC(1054, false, Material.iron)).setUnlocalizedName("metalplatform").setTextureName("countercraft:metalplatform");
      GameRegistry.registerBlock(metalPlatform, "cc.block.metalplatform");
      LanguageRegistry.addName(metalPlatform, "Metal Platform");
      glassSlab = (new BlockSlabOpaqueCC(1055, false, Material.glass)).setUnlocalizedName("glassslab").setTextureName("countercraft:glassslab");
      GameRegistry.registerBlock(glassSlab, "cc.block.glassSlab");
      LanguageRegistry.addName(glassSlab, "Glass Slab");
      Item.itemsList[stainedClaySlab.blockID] = (new ItemSlab(stainedClaySlab.blockID - 256, stainedClaySlab, stainedClayDoubleSlab, false)).setUnlocalizedName("stainedClaySlab");
      Item.itemsList[stainedClayDoubleSlab.blockID] = (new ItemSlab(stainedClayDoubleSlab.blockID - 256, stainedClaySlab, stainedClayDoubleSlab, true)).setUnlocalizedName("stainedClayDoubleSlab");
      Item.itemsList[stainedClaySlab2.blockID] = (new ItemSlab(stainedClaySlab2.blockID - 256, stainedClaySlab2, stainedClayDoubleSlab2, false)).setUnlocalizedName("stainedClaySlab2");
      Item.itemsList[stainedClayDoubleSlab2.blockID] = (new ItemSlab(stainedClayDoubleSlab2.blockID - 256, stainedClaySlab2, stainedClayDoubleSlab2, true)).setUnlocalizedName("stainedClayDoubleSlab2");
      GameRegistry.registerBlock(sandbag, "cc.block.sandbag");
      LanguageRegistry.addName(sandbag, "Sandbag");
      GameRegistry.registerBlock(road, "cc.block.road");
      LanguageRegistry.addName(road, "Road");
      GameRegistry.registerBlock(roadSolid, "cc.block.road.broken");
      LanguageRegistry.addName(roadSolid, "Broken Road");
      GameRegistry.registerBlock(roadBroken, "cc.block.road.solid");
      LanguageRegistry.addName(roadBroken, "Solid Road");
      emitterSoundBirds = new BlockEmitterSound(1601, "birds", 20);
      GameRegistry.registerBlock(emitterSoundBirds, "cc.block.emitter.sound.birds");
      LanguageRegistry.addName(emitterSoundBirds, "Mono Emitter Sound (birds)");
      emitterSoundWind = new BlockEmitterSound(1602, "wind", 5);
      GameRegistry.registerBlock(emitterSoundWind, "cc.block.emitter.sound.wind");
      LanguageRegistry.addName(emitterSoundWind, "Stereo Emitter Sound (wind)");
      emitterSoundHelicopter = new BlockEmitterSound(1603, "helicopter", 75);
      GameRegistry.registerBlock(emitterSoundHelicopter, "cc.block.emitter.sound.helicopter");
      LanguageRegistry.addName(emitterSoundHelicopter, "Mono Emitter Sound (helicopter)");
      emitterSoundDog = new BlockEmitterSound(1604, "dog", 50);
      GameRegistry.registerBlock(emitterSoundDog, "cc.block.emitter.sound.dog");
      LanguageRegistry.addName(emitterSoundDog, "Mono Emitter Sound (dog)");
      emitterSoundWar = new BlockEmitterSound(1605, "war", 5);
      GameRegistry.registerBlock(emitterSoundWar, "cc.block.emitter.sound.war");
      LanguageRegistry.addName(emitterSoundWar, "Stereo Emitter Sound (war)");
      emitterSoundNight = new BlockEmitterSound(1606, "night", 5);
      GameRegistry.registerBlock(emitterSoundNight, "cc.block.emitter.sound.night");
      LanguageRegistry.addName(emitterSoundNight, "Stereo Emitter Sound (night)");
      emitterSoundCity = new BlockEmitterSound(1607, "city", 5);
      GameRegistry.registerBlock(emitterSoundCity, "cc.block.emitter.sound.city");
      LanguageRegistry.addName(emitterSoundCity, "Stereo Emitter Sound (city)");
      emitterSoundShop = new BlockEmitterSound(1608, "shop", 4);
      GameRegistry.registerBlock(emitterSoundShop, "cc.block.emitter.sound.shop");
      LanguageRegistry.addName(emitterSoundShop, "Stereo Emitter Sound (shop)");
      GameRegistry.registerTileEntity(TileEntityBarrier.class, "barrier");
      GameRegistry.registerTileEntity(TileEntityPropCrateWood.class, "propcratewood");
      GameRegistry.registerTileEntity(TileEntityPropCrateMetal.class, "propcratemetal");
      GameRegistry.registerTileEntity(TileEntityPropBarrel.class, "propbarrel");
      mapBarrier = (new BlockMapBarrier(1500)).setHardness(0.3F).setUnlocalizedName("barrier");
      GameRegistry.registerBlock(mapBarrier, "cc.block.barrier");
      LanguageRegistry.addName(mapBarrier, "Barrier");
      benchMenu = (new BlockBench(1501)).setHardness(5.0F).setUnlocalizedName("cc.bench");
      GameRegistry.registerBlock(benchMenu, "cc.block.bench");
      LanguageRegistry.addName(benchMenu, "Menu Bench");
      decalSiteA = (new BlockDecal(1806, "sitea")).setHardness(0.3F);
      GameRegistry.registerBlock(decalSiteA, "cc.block.decals.sitea");
      LanguageRegistry.addName(decalSiteA, "Decal (A Site)");
      decalSiteB = (new BlockDecal(1807, "siteb")).setHardness(0.3F);
      GameRegistry.registerBlock(decalSiteB, "cc.block.decals.siteb");
      LanguageRegistry.addName(decalSiteB, "Decal (B Site)");
      decalArrowUp = (new BlockDecal(1808, "arrowup")).setHardness(0.3F);
      GameRegistry.registerBlock(decalArrowUp, "cc.block.decals.arrowup");
      LanguageRegistry.addName(decalArrowUp, "Decal (Arrow Up)");
      decalArrowDown = (new BlockDecal(1809, "arrowdown")).setHardness(0.3F);
      GameRegistry.registerBlock(decalArrowDown, "cc.block.decals.arrowdown");
      LanguageRegistry.addName(decalArrowDown, "Decal (Arrow Down)");
      decalArrowLeft = (new BlockDecal(1810, "arrowleft")).setHardness(0.3F);
      GameRegistry.registerBlock(decalArrowLeft, "cc.block.decals.arrowleft");
      LanguageRegistry.addName(decalArrowLeft, "Decal (Arrow Left)");
      decalArrowRight = (new BlockDecal(1811, "arrowright")).setHardness(0.3F);
      GameRegistry.registerBlock(decalArrowRight, "cc.block.decals.arrowright");
      LanguageRegistry.addName(decalArrowRight, "Decal (Arrow Right)");

      for(int i = 0; i < 16; ++i) {
         String clayName = ItemDye.dyeColorNames[~i & 15].substring(0, 1).toUpperCase() + ItemDye.dyeColorNames[~i & 15].substring(1, ItemDye.dyeColorNames[~i & 15].length());
         if (i < 7) {
            LanguageRegistry.addName(new ItemStack(stainedClaySlab.blockID, 1, i), clayName + " Stained Clay Slab");
         } else {
            LanguageRegistry.addName(new ItemStack(stainedClaySlab2.blockID, 1, i - 7), clayName + " Stained Clay Slab");
         }
      }

   }
}
